[window]
opacity = 0.95

[colors]
transparent_background_colors = true

[colors.primary]
background  = "#0F1117"
foreground  = "#E4DCD0"

[colors.cursor]
text   = "#0F1117"
cursor = "#E5B869"

[colors.selection]
text       = "#FAF5EE"
background = "#242A38"

[colors.normal]
black   = "#181B24"
red     = "#D45D68"
green   = "#63A87E"
yellow  = "#E5B869"
blue    = "#6B95D6"
magenta = "#B382D9"
cyan    = "#5BBBB2"
white   = "#E4DCD0"

[colors.bright]
black   = "#545A6C"
red     = "#E57580"
green   = "#78BE93"
yellow  = "#F2C77D"
blue    = "#82A9E5"
magenta = "#C497E8"
cyan    = "#72CFC7"
white   = "#FAF5EE"
