[primary]
background  = "#171515"
foreground  = "#e0d6c2"

[normal]
black       = "#232020"
red         = "#ae0001"
green       = "#1a472a"
yellow      = "#ecb939"
blue        = "#224f85"
magenta     = "#725e87"
cyan        = "#3a6e6e"
white       = "#c4bca6"

[bright]
black       = "#5c5555"
red         = "#c47f7f"
green       = "#3a6e6e"
yellow      = "#dba25a"
blue        = "#7e97ba"
magenta     = "#d18c9f"
cyan        = "#9ea3ad"
white       = "#e0d6c2"
