# Font Configuration
font-family = Iosevka

# Background: "Old Library" Dark
background = #171515
foreground = #e0d6c2
selection-background = #3a2e2e
selection-foreground = #e0d6c2
cursor-color = #ecb939

# Standard colors
palette = 0=#232020
palette = 1=#ae0001
palette = 2=#1a472a
palette = 3=#ecb939
palette = 4=#224f85
palette = 5=#725e87
palette = 6=#3a6e6e
palette = 7=#c4bca6

# Bright colors
palette = 8=#5c5555
palette = 9=#c47f7f
palette = 10=#3a6e6e
palette = 11=#dba25a
palette = 12=#7e97ba
palette = 13=#d18c9f
palette = 14=#9ea3ad
palette = 15=#e0d6c2
