background = #0F1117
foreground = #E4DCD0
selection-background = #242A38
selection-foreground = #FAF5EE
cursor-color = #E5B869

# Standard colors
palette = 0=#181B24
palette = 1=#D45D68
palette = 2=#63A87E
palette = 3=#E5B869
palette = 4=#6B95D6
palette = 5=#B382D9
palette = 6=#5BBBB2
palette = 7=#E4DCD0

# Bright colors
palette = 8=#545A6C
palette = 9=#E57580
palette = 10=#78BE93
palette = 11=#F2C77D
palette = 12=#82A9E5
palette = 13=#C497E8
palette = 14=#72CFC7
palette = 15=#FAF5EE
