# Font Configuration
#font-family = Iosevka

# Background and foreground colors
background = #0c0e14
foreground = #e0d6c2
selection-background = #2f3340
selection-foreground = #e0d6c2
cursor-color = #ecb939

# Standard colors
palette = 0=#1a1e29
palette = 1=#ae0001
palette = 2=#1a472a
palette = 3=#ecb939
palette = 4=#224f85
palette = 5=#725e87
palette = 6=#3a6e6e
palette = 7=#c4bca6

# Bright colors
palette = 8=#5a5e6b
palette = 9=#c47f7f
palette = 10=#3a6e6e
palette = 11=#dba25a
palette = 12=#7e97ba
palette = 13=#d18c9f
palette = 14=#9ea3ad
palette = 15=#e0d6c2
