# Hogwarts Night - Hyprlock Colors
$color = rgba(0c0e14ff)
$inner_color = rgba(0c0e14a9)
$outer_color = rgba(ecb939d9)      # Snitch/Hufflepuff Gold
$font_color = rgba(e0d6c2d9)
$placeholder_color = rgba(e0d6c2b3)
$check_color = rgba(224f85ff)      # Ravenclaw Blue
