# Hogwarts Night - Hyprlock Colors
$color = rgba(0F1117ff)
$inner_color = rgba(0F1117dd)
$outer_color = rgba(E5B869ee)
$font_color = rgba(E4DCD0ff)
$placeholder_color = rgba(82899Caa)
$check_color = rgba(6B95D6ff)
