background            #0c0e14
foreground            #e0d6c2
selection_background  #2f3340
selection_foreground  #e0d6c2
cursor                #ecb939
cursor_text_color     #0c0e14
url_color             #7e97ba

# black (Dark Arts / Shadows)
color0  #1a1e29
color8  #5a5e6b

# red (Gryffindor)
color1  #ae0001
color9  #c47f7f

# green (Slytherin / Potions)
color2  #1a472a
color10 #3a6e6e

# yellow (Hufflepuff / Golden Snitch)
color3  #ecb939
color11 #dba25a

# blue (Ravenclaw)
color4  #224f85
color12 #7e97ba

# magenta (Spells)
color5  #725e87
color13 #d18c9f

# cyan (Patronus / Ghosts)
color6  #3a6e6e
color14 #9ea3ad

# white (Parchment)
color7  #c4bca6
color15 #e0d6c2
