background            #0F1117
foreground            #E4DCD0
selection_background  #242A38
selection_foreground  #FAF5EE
cursor                #E5B869
cursor_text_color     #0F1117
url_color             #6B95D6

# black
color0  #181B24
color8  #545A6C

# red (Gryffindor Crimson)
color1  #D45D68
color9  #E57580

# green (Slytherin Emerald)
color2  #63A87E
color10 #78BE93

# yellow (Golden Snitch)
color3  #E5B869
color11 #F2C77D

# blue (Ravenclaw Azure)
color4  #6B95D6
color12 #82A9E5

# magenta (Mystic Amethyst)
color5  #B382D9
color13 #C497E8

# cyan (Patronus Silver-Teal)
color6  #5BBBB2
color14 #72CFC7

# white (Warm Parchment)
color7  #E4DCD0
color15 #FAF5EE
