[meta]
version = 1
name = "Hogwarts Night"
description = "An aesthetic midnight Harry Potter system theme."
variant = "dark"
inherits = "vicinae-dark"

[colors.core]
background = "#0F1117"
foreground = "#E4DCD0"
secondary_background = "#181B24"
border = "#242A38"
accent = "#E5B869"

[colors.list.item.hover]
background = "#181B24"
foreground = "#FAF5EE"

[colors.list.item.selection]
background = "#242A38"
foreground = "#FAF5EE"

[colors.accents]
blue = "#6B95D6"
green = "#63A87E"
magenta = "#B382D9"
orange = "#E28E58"
purple = "#B382D9"
red = "#D45D68"
yellow = "#E5B869"
cyan = "#5BBBB2"
